#!/bin/bash
export SPARK_HOME=/home/jmarcus/projects/github/stream-kde/spark/target/scala-2.9.2/
export SPARK_JAR=/home/jmarcus/projects/github/stream-kde/spark/target/scala-2.9.2/kde_2.9.2-0.1.jar


# seattle 911
sbt12 "run local[4] -13630000,6014000,-13604000,6071000 50"
