#!/bin/bash
export SPARK_HOME=/Users/jeremy/Documents/Development/github/stream-kde/spark/target/scala-2.9.2/
export SPARK_JAR=/Users/jeremy/Documents/Development/github/stream-kde/spark/target/scala-2.9.2/kde_2.9.2-0.1.jar


# seattle 911
exec sbt "run local[4] -13630000,5983000,-13605000,6039000 100"